In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[7]

7

In [6]:
# 3, 4, 5
arr[3:6] # 3 dahi, 6 hariç index

array([3, 4, 5])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[3] = 23

In [9]:
arr

array([ 0,  1,  2, 23,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[5:] = 30

In [11]:
arr

array([ 0,  1,  2, 23,  4, 30, 30, 30, 30, 30, 30])

In [12]:
yeni_arr = arr

In [13]:
yeni_arr

array([ 0,  1,  2, 23,  4, 30, 30, 30, 30, 30, 30])

In [14]:
yeni_arr[0] = 18

In [15]:
yeni_arr

array([18,  1,  2, 23,  4, 30, 30, 30, 30, 30, 30])

In [16]:
arr # arr değerleri de değişir yeni_arr üzerindeki değişiklikler sonrası

array([18,  1,  2, 23,  4, 30, 30, 30, 30, 30, 30])

In [17]:
b_arr = arr.copy() # b_arr => arr'ın kopyası ama bağımsız

In [18]:
b_arr

array([18,  1,  2, 23,  4, 30, 30, 30, 30, 30, 30])

In [19]:
b_arr[0] = 12

In [20]:
b_arr

array([12,  1,  2, 23,  4, 30, 30, 30, 30, 30, 30])

In [21]:
arr

array([18,  1,  2, 23,  4, 30, 30, 30, 30, 30, 30])

In [26]:
arr2 = np.arange(1,101)

In [27]:
arr2.shape

(100,)

In [28]:
arr3 = arr2.reshape((20,5))

In [29]:
arr3

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [31]:
arr3[4:6,2:4] # 4 ve 5. satırları ile 2 ve 3. kolonların kesişim matrisi

array([[23, 24],
       [28, 29]])

In [35]:
arr3[arr3 < 40].shape

(39,)

In [36]:
arr = np.arange(0,10)

In [37]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b_arr = np.arange(10,20)

In [39]:
b_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
arr * b_arr

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [41]:
arr + b_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [42]:
b_arr - arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [43]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [44]:
arr**(1/2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [45]:
arr^3

array([ 3,  2,  1,  0,  7,  6,  5,  4, 11, 10], dtype=int32)

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr^3 # bitwise XOR (üst alma değil!)

array([ 3,  2,  1,  0,  7,  6,  5,  4, 11, 10], dtype=int32)

In [48]:
type(arr)

numpy.ndarray

In [49]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [50]:
arr ** (1/2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [51]:
np.max(arr)

9

In [55]:
print(np.array([1,2,3.,4])) # numpy array'leri homojen veri tipi içerir. Farklı farklı veri tipleri yer almaz.

[1. 2. 3. 4.]


In [57]:
np.array(['a','b',1]) # string veri türü içerebilir

array(['a', 'b', '1'], dtype='<U11')

In [52]:
# !pip install pandas

In [58]:
import pandas as pd

In [60]:
# data frame
matris = np.random.randn(5,4)

In [61]:
matris

array([[-1.46365455e+00, -2.25304109e-01, -3.01440477e-01,
        -4.15726317e-01],
       [ 1.82922968e+00, -6.66823083e-01,  2.09745521e+00,
        -3.72121618e-01],
       [-7.92396288e-04, -4.35552114e-01, -4.77937852e-01,
         2.53535876e-01],
       [ 2.59166207e+00,  1.06091039e+00, -9.72098835e-01,
        -8.15368726e-01],
       [-4.60903946e-01,  1.00896624e+00,  5.68398220e-01,
         1.48460610e+00]])

In [63]:
df = pd.DataFrame(matris, index=[1,2,3,4,5], columns=['A','B','C','D'])

In [64]:
df.head() # ilk 5 satır listelenir

A         B         C         D
1 -1.463655 -0.225304 -0.301440 -0.415726
2  1.829230 -0.666823  2.097455 -0.372122
3 -0.000792 -0.435552 -0.477938  0.253536
4  2.591662  1.060910 -0.972099 -0.815369
5 -0.460904  1.008966  0.568398  1.484606

In [66]:
df = pd.DataFrame(matris, index=['T','W','X','Y','Z'], columns=['A','B','C','D'])

In [68]:
df.head()

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [67]:
df.head(2) # ilk 2 satır listelenir

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122

In [69]:
df.tail(3) # son 3 satır listelenir

A         B         C         D
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [70]:
df['B'] # B kolonu seçilir

T   -0.225304
W   -0.666823
X   -0.435552
Y    1.060910
Z    1.008966
Name: B, dtype: float64

In [73]:
df[['B','D']] # B ve D kolonları

B         D
T -0.225304 -0.415726
W -0.666823 -0.372122
X -0.435552  0.253536
Y  1.060910 -0.815369
Z  1.008966  1.484606

In [74]:
type(df)

pandas.core.frame.DataFrame

In [75]:
type(df['B']) # data type => Series

pandas.core.series.Series

In [76]:
type(df[['B']]) # data type => DataFrame

pandas.core.frame.DataFrame

In [79]:
df['yeni'] = df['B'] + df['D'] # dataframe'e yeni kolon ekleme

In [80]:
df

A         B         C         D      yeni
T -1.463655 -0.225304 -0.301440 -0.415726 -0.641030
W  1.829230 -0.666823  2.097455 -0.372122 -1.038945
X -0.000792 -0.435552 -0.477938  0.253536 -0.182016
Y  2.591662  1.060910 -0.972099 -0.815369  0.245542
Z -0.460904  1.008966  0.568398  1.484606  2.493572

In [81]:
df.drop('yeni',axis=1)

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [82]:
df

A         B         C         D      yeni
T -1.463655 -0.225304 -0.301440 -0.415726 -0.641030
W  1.829230 -0.666823  2.097455 -0.372122 -1.038945
X -0.000792 -0.435552 -0.477938  0.253536 -0.182016
Y  2.591662  1.060910 -0.972099 -0.815369  0.245542
Z -0.460904  1.008966  0.568398  1.484606  2.493572

In [83]:
df.drop('yeni',axis=1,inplace=True)

In [84]:
df

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [85]:
df.drop('Y', axis=0)

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Z -0.460904  1.008966  0.568398  1.484606

In [86]:
# W satırına erişim için
df.loc['X'] # index adı ile

A   -0.000792
B   -0.435552
C   -0.477938
D    0.253536
Name: X, dtype: float64

In [87]:
df.iloc[2] # index numarası ile

A   -0.000792
B   -0.435552
C   -0.477938
D    0.253536
Name: X, dtype: float64

In [89]:
df.loc[['X','Z']]

A         B         C         D
X -0.000792 -0.435552 -0.477938  0.253536
Z -0.460904  1.008966  0.568398  1.484606

In [90]:
df

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [91]:
df.loc[['X','Z'],['B','D']]

B         D
X -0.435552  0.253536
Z  1.008966  1.484606

In [93]:
df.loc[['X','Z']][['B','D']]

B         D
X -0.435552  0.253536
Z  1.008966  1.484606

In [94]:
df

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [95]:
df>0

A      B      C      D
T  False  False  False  False
W   True  False   True  False
X  False  False  False   True
Y   True   True  False  False
Z  False   True   True   True

In [96]:
df[df>0] # df'in hücre değerlerinin sıfırdan büyük olanlar

A         B         C         D
T       NaN       NaN       NaN       NaN
W  1.829230       NaN  2.097455       NaN
X       NaN       NaN       NaN  0.253536
Y  2.591662  1.060910       NaN       NaN
Z       NaN  1.008966  0.568398  1.484606

In [97]:
df

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [99]:
df.describe() # dataframe hakkında özet istatistik

A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.499108  0.148439  0.182875  0.026985
std    1.671225  0.824393  1.206176  0.900114
min   -1.463655 -0.666823 -0.972099 -0.815369
25%   -0.460904 -0.435552 -0.477938 -0.415726
50%   -0.000792 -0.225304 -0.301440 -0.372122
75%    1.829230  1.008966  0.568398  0.253536
max    2.591662  1.060910  2.097455  1.484606

In [100]:
df.info() # dataframe datatype vb

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, T to Z
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      float64
 3   D       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [101]:
df2 = df[df>0]

In [102]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, T to Z
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       2 non-null      float64
 1   B       2 non-null      float64
 2   C       2 non-null      float64
 3   D       2 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [103]:
df2

A         B         C         D
T       NaN       NaN       NaN       NaN
W  1.829230       NaN  2.097455       NaN
X       NaN       NaN       NaN  0.253536
Y  2.591662  1.060910       NaN       NaN
Z       NaN  1.008966  0.568398  1.484606

In [104]:
df2['E'] = df2['A'] + df2['D']

In [105]:
df2.head()

A         B         C         D   E
T       NaN       NaN       NaN       NaN NaN
W  1.829230       NaN  2.097455       NaN NaN
X       NaN       NaN       NaN  0.253536 NaN
Y  2.591662  1.060910       NaN       NaN NaN
Z       NaN  1.008966  0.568398  1.484606 NaN

In [106]:
df2.fillna(0)

A         B         C         D    E
T  0.000000  0.000000  0.000000  0.000000  0.0
W  1.829230  0.000000  2.097455  0.000000  0.0
X  0.000000  0.000000  0.000000  0.253536  0.0
Y  2.591662  1.060910  0.000000  0.000000  0.0
Z  0.000000  1.008966  0.568398  1.484606  0.0

In [107]:
df

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [108]:
df.reset_index()

index         A         B         C         D
0     T -1.463655 -0.225304 -0.301440 -0.415726
1     W  1.829230 -0.666823  2.097455 -0.372122
2     X -0.000792 -0.435552 -0.477938  0.253536
3     Y  2.591662  1.060910 -0.972099 -0.815369
4     Z -0.460904  1.008966  0.568398  1.484606

In [109]:
df

A         B         C         D
T -1.463655 -0.225304 -0.301440 -0.415726
W  1.829230 -0.666823  2.097455 -0.372122
X -0.000792 -0.435552 -0.477938  0.253536
Y  2.591662  1.060910 -0.972099 -0.815369
Z -0.460904  1.008966  0.568398  1.484606

In [110]:
df['D'].max()

1.4846061012288234

In [111]:
df.max() # Kolonların maximum değerleri

A    2.591662
B    1.060910
C    2.097455
D    1.484606
dtype: float64

In [113]:
df.max(axis=1) # Satırların maximum değerleri

T   -0.225304
W    2.097455
X    0.253536
Y    2.591662
Z    1.484606
dtype: float64

## Gruplama (Group by)

In [118]:
data = {'Sirket':['ABC','XYZ','DED','XDAK','DED','BJK'],
       'Kisi':['Ali','Mehmet','Ayşe','Ceren','Barış','Cenk'],
       'Butce':[200,500,300,230,120,450]}

In [115]:
type(data)

dict

In [119]:
df = pd.DataFrame(data)

In [124]:
df.head(6)

Sirket    Kisi  Butce
0    ABC     Ali    200
1    XYZ  Mehmet    500
2    DED    Ayşe    300
3   XDAK   Ceren    230
4    DED   Barış    120
5    BJK    Cenk    450

In [122]:
sirket_gr = df.groupby('Sirket')

In [123]:
sirket_gr.mean()

Butce
Sirket       
ABC     200.0
BJK     450.0
DED     210.0
XDAK    230.0
XYZ     500.0

## Dataframe birleştirme (Merge, Join, Concatanate)

In [127]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']}, index=[0, 1, 2, 3])

In [129]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C':['C4','C5','C6','C7'],
                    'D':['D4','D5','D6','D7']}, index=[4, 5, 6, 7])

In [130]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                    'B':['B8','B9','B10','B11'],
                    'C':['C8','C9','C10','C11'],
                    'D':['D8','D9','D10','D11']}, index=[8, 9, 10, 11])

In [131]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [132]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [133]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [134]:
# dataframe'leri alt alta birleştirme
df = pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [135]:
pd.concat([df1, df2, df3], axis=1) # dataframe'ler yan yana

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

## Join 

In [136]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']}, index=[0, 1, 2, 3])

In [137]:
df2 = pd.DataFrame({'A2':['A4','A5','A6','A7'],
                    'B2':['B4','B5','B6','B7'],
                    'C2':['C4','C5','C6','C7'],
                    'D2':['D4','D5','D6','D7']}, index=[0, 1, 2, 3])

In [138]:
df1.head()

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [139]:
df2.head()

A2  B2  C2  D2
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [141]:
df1.join(df2)

A   B   C   D  A2  B2  C2  D2
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

In [142]:
df3 = pd.DataFrame({'A2':['A4','A5','A6','A7'],
                    'B2':['B4','B5','B6','B7'],
                    'C2':['C4','C5','C6','C7'],
                    'D2':['D4','D5','D6','D7']}, index=[0, 1, 2, 4])

In [143]:
df1.join(df3)

A   B   C   D   A2   B2   C2   D2
0  A0  B0  C0  D0   A4   B4   C4   D4
1  A1  B1  C1  D1   A5   B5   C5   D5
2  A2  B2  C2  D2   A6   B6   C6   D6
3  A3  B3  C3  D3  NaN  NaN  NaN  NaN

In [144]:
df1.join(df3, how='outer')

A    B    C    D   A2   B2   C2   D2
0   A0   B0   C0   D0   A4   B4   C4   D4
1   A1   B1   C1   D1   A5   B5   C5   D5
2   A2   B2   C2   D2   A6   B6   C6   D6
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A7   B7   C7   D7

## Uygulamalar

In [145]:
# Uygulama-1
# Bütün hücre değerleri 1 olan 10 x 4 boyutlarında bir dataframe oluşturunuz. Kolon isimleri: A, B, C,D

In [149]:
np.ones([5,3]) # ipucu

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [148]:
# ipucu: df = pd.DataFrame(matris, index=[1,2,3,4,5], columns=['A','B','C','D'])

In [150]:
# Kaan
matris = np.ones([10,4])
df = pd.DataFrame(matris, index = [1,2,3,4,5,6,7,8,9,10], columns = ['A','B','C','D'])

In [151]:
df

A    B    C    D
1   1.0  1.0  1.0  1.0
2   1.0  1.0  1.0  1.0
3   1.0  1.0  1.0  1.0
4   1.0  1.0  1.0  1.0
5   1.0  1.0  1.0  1.0
6   1.0  1.0  1.0  1.0
7   1.0  1.0  1.0  1.0
8   1.0  1.0  1.0  1.0
9   1.0  1.0  1.0  1.0
10  1.0  1.0  1.0  1.0

In [152]:
pd.DataFrame(matris, index = range(1,11), columns = ['A','B','C','D'])

A    B    C    D
1   1.0  1.0  1.0  1.0
2   1.0  1.0  1.0  1.0
3   1.0  1.0  1.0  1.0
4   1.0  1.0  1.0  1.0
5   1.0  1.0  1.0  1.0
6   1.0  1.0  1.0  1.0
7   1.0  1.0  1.0  1.0
8   1.0  1.0  1.0  1.0
9   1.0  1.0  1.0  1.0
10  1.0  1.0  1.0  1.0

In [153]:
pd.DataFrame(matris, index = range(1,11), columns = 'A B C D'.split())

A    B    C    D
1   1.0  1.0  1.0  1.0
2   1.0  1.0  1.0  1.0
3   1.0  1.0  1.0  1.0
4   1.0  1.0  1.0  1.0
5   1.0  1.0  1.0  1.0
6   1.0  1.0  1.0  1.0
7   1.0  1.0  1.0  1.0
8   1.0  1.0  1.0  1.0
9   1.0  1.0  1.0  1.0
10  1.0  1.0  1.0  1.0

In [154]:
# Uygulama-2
# Yeni bir 'E' kolonu ekleyin ve değerleri A ve D kolonlarının toplamı olsun.

In [155]:
df['E'] = df['A'] + df['D']

In [156]:
df.head()

A    B    C    D    E
1  1.0  1.0  1.0  1.0  2.0
2  1.0  1.0  1.0  1.0  2.0
3  1.0  1.0  1.0  1.0  2.0
4  1.0  1.0  1.0  1.0  2.0
5  1.0  1.0  1.0  1.0  2.0

In [158]:
# Uygulama-3
# yeni bir F kolonu oluşturun ve bütün değerleri   olsun.

In [160]:
# Fatih Çelebi
df['F']=4.5

In [161]:
df

A    B    C    D    E    F
1   1.0  1.0  1.0  1.0  2.0  4.5
2   1.0  1.0  1.0  1.0  2.0  4.5
3   1.0  1.0  1.0  1.0  2.0  4.5
4   1.0  1.0  1.0  1.0  2.0  4.5
5   1.0  1.0  1.0  1.0  2.0  4.5
6   1.0  1.0  1.0  1.0  2.0  4.5
7   1.0  1.0  1.0  1.0  2.0  4.5
8   1.0  1.0  1.0  1.0  2.0  4.5
9   1.0  1.0  1.0  1.0  2.0  4.5
10  1.0  1.0  1.0  1.0  2.0  4.5

In [162]:
# Uygulama
# C kolonu 5 no'lu index hücre değeri 1.0 => 8.0
# ipucu: loc veya iloc

In [163]:
# Kaan
df.loc[[5],['C']] = 8

In [164]:
df

A    B    C    D    E    F
1   1.0  1.0  1.0  1.0  2.0  4.5
2   1.0  1.0  1.0  1.0  2.0  4.5
3   1.0  1.0  1.0  1.0  2.0  4.5
4   1.0  1.0  1.0  1.0  2.0  4.5
5   1.0  1.0  8.0  1.0  2.0  4.5
6   1.0  1.0  1.0  1.0  2.0  4.5
7   1.0  1.0  1.0  1.0  2.0  4.5
8   1.0  1.0  1.0  1.0  2.0  4.5
9   1.0  1.0  1.0  1.0  2.0  4.5
10  1.0  1.0  1.0  1.0  2.0  4.5

In [165]:
df.loc[[3],['E']] = 4

In [166]:
df.loc[[3], ['B']] = 10

In [169]:
df.loc[[3],['D']] = 2

In [170]:
df

A     B    C    D    E    F
1   1.0   1.0  1.0  1.0  2.0  4.5
2   1.0   1.0  1.0  1.0  2.0  4.5
3   1.0  10.0  1.0  2.0  4.0  4.5
4   1.0   1.0  1.0  1.0  2.0  4.5
5   1.0   1.0  8.0  1.0  2.0  4.5
6   1.0   1.0  1.0  1.0  2.0  4.5
7   1.0   1.0  1.0  1.0  2.0  4.5
8   1.0   1.0  1.0  1.0  2.0  4.5
9   1.0   1.0  1.0  1.0  2.0  4.5
10  1.0   1.0  1.0  1.0  2.0  4.5

In [171]:
# B kolon değerlerinin ORTALAMASI kaçtır?

In [172]:
df['C'].mean() 

1.7

In [173]:
# Nilda
df['B'].mean()

1.9

In [176]:
# F kolonunu dataframe'den çıkarınız (drop)
# ipucu: df.drop(['B', 'C'], axis=1)
df.drop(['F'], axis=1)

A     B    C    D    E
1   1.0   1.0  1.0  1.0  2.0
2   1.0   1.0  1.0  1.0  2.0
3   1.0  10.0  1.0  2.0  4.0
4   1.0   1.0  1.0  1.0  2.0
5   1.0   1.0  8.0  1.0  2.0
6   1.0   1.0  1.0  1.0  2.0
7   1.0   1.0  1.0  1.0  2.0
8   1.0   1.0  1.0  1.0  2.0
9   1.0   1.0  1.0  1.0  2.0
10  1.0   1.0  1.0  1.0  2.0

In [177]:
df

A     B    C    D    E    F
1   1.0   1.0  1.0  1.0  2.0  4.5
2   1.0   1.0  1.0  1.0  2.0  4.5
3   1.0  10.0  1.0  2.0  4.0  4.5
4   1.0   1.0  1.0  1.0  2.0  4.5
5   1.0   1.0  8.0  1.0  2.0  4.5
6   1.0   1.0  1.0  1.0  2.0  4.5
7   1.0   1.0  1.0  1.0  2.0  4.5
8   1.0   1.0  1.0  1.0  2.0  4.5
9   1.0   1.0  1.0  1.0  2.0  4.5
10  1.0   1.0  1.0  1.0  2.0  4.5

In [178]:
df.drop('F', axis = 1, inplace = True)

In [179]:
df

A     B    C    D    E
1   1.0   1.0  1.0  1.0  2.0
2   1.0   1.0  1.0  1.0  2.0
3   1.0  10.0  1.0  2.0  4.0
4   1.0   1.0  1.0  1.0  2.0
5   1.0   1.0  8.0  1.0  2.0
6   1.0   1.0  1.0  1.0  2.0
7   1.0   1.0  1.0  1.0  2.0
8   1.0   1.0  1.0  1.0  2.0
9   1.0   1.0  1.0  1.0  2.0
10  1.0   1.0  1.0  1.0  2.0

In [180]:
yk = pd.DataFrame()

In [181]:
# Uygulama
# df'in değeri 1'den büyük olanları filtreleyiniz.
# ipucu: df > 1 => True/False

In [182]:
# Kaan
df = df[df > 1]

In [183]:
df

A     B    C    D    E
1  NaN   NaN  NaN  NaN  2.0
2  NaN   NaN  NaN  NaN  2.0
3  NaN  10.0  NaN  2.0  4.0
4  NaN   NaN  NaN  NaN  2.0
5  NaN   NaN  8.0  NaN  2.0
6  NaN   NaN  NaN  NaN  2.0
7  NaN   NaN  NaN  NaN  2.0
8  NaN   NaN  NaN  NaN  2.0
9  NaN   NaN  NaN  NaN  2.0
10 NaN   NaN  NaN  NaN  2.0

In [184]:
# NaN değerleri => 0 yapınız.

In [185]:
df.fillna(0)

A     B    C    D    E
1   0.0   0.0  0.0  0.0  2.0
2   0.0   0.0  0.0  0.0  2.0
3   0.0  10.0  0.0  2.0  4.0
4   0.0   0.0  0.0  0.0  2.0
5   0.0   0.0  8.0  0.0  2.0
6   0.0   0.0  0.0  0.0  2.0
7   0.0   0.0  0.0  0.0  2.0
8   0.0   0.0  0.0  0.0  2.0
9   0.0   0.0  0.0  0.0  2.0
10  0.0   0.0  0.0  0.0  2.0

In [186]:
df

A     B    C    D    E
1  NaN   NaN  NaN  NaN  2.0
2  NaN   NaN  NaN  NaN  2.0
3  NaN  10.0  NaN  2.0  4.0
4  NaN   NaN  NaN  NaN  2.0
5  NaN   NaN  8.0  NaN  2.0
6  NaN   NaN  NaN  NaN  2.0
7  NaN   NaN  NaN  NaN  2.0
8  NaN   NaN  NaN  NaN  2.0
9  NaN   NaN  NaN  NaN  2.0
10 NaN   NaN  NaN  NaN  2.0

In [187]:
df = df.fillna(0)
# df.fillna(0, inplace=True)

In [188]:
df

A     B    C    D    E
1   0.0   0.0  0.0  0.0  2.0
2   0.0   0.0  0.0  0.0  2.0
3   0.0  10.0  0.0  2.0  4.0
4   0.0   0.0  0.0  0.0  2.0
5   0.0   0.0  8.0  0.0  2.0
6   0.0   0.0  0.0  0.0  2.0
7   0.0   0.0  0.0  0.0  2.0
8   0.0   0.0  0.0  0.0  2.0
9   0.0   0.0  0.0  0.0  2.0
10  0.0   0.0  0.0  0.0  2.0

In [189]:
# Uygulama
# df verilerini kullanarak yeni bir dataframe oluşturunuz ama yeni dataframe'de yapılacak
# değişiklikler df'i değiştirmesin.

In [190]:
df2 = df

In [191]:
df2

A     B    C    D    E
1   0.0   0.0  0.0  0.0  2.0
2   0.0   0.0  0.0  0.0  2.0
3   0.0  10.0  0.0  2.0  4.0
4   0.0   0.0  0.0  0.0  2.0
5   0.0   0.0  8.0  0.0  2.0
6   0.0   0.0  0.0  0.0  2.0
7   0.0   0.0  0.0  0.0  2.0
8   0.0   0.0  0.0  0.0  2.0
9   0.0   0.0  0.0  0.0  2.0
10  0.0   0.0  0.0  0.0  2.0

In [192]:
df

A     B    C    D    E
1   0.0   0.0  0.0  0.0  2.0
2   0.0   0.0  0.0  0.0  2.0
3   0.0  10.0  0.0  2.0  4.0
4   0.0   0.0  0.0  0.0  2.0
5   0.0   0.0  8.0  0.0  2.0
6   0.0   0.0  0.0  0.0  2.0
7   0.0   0.0  0.0  0.0  2.0
8   0.0   0.0  0.0  0.0  2.0
9   0.0   0.0  0.0  0.0  2.0
10  0.0   0.0  0.0  0.0  2.0

In [193]:
df2.loc[[2],'A'] = 1

In [194]:
df2

A     B    C    D    E
1   0.0   0.0  0.0  0.0  2.0
2   1.0   0.0  0.0  0.0  2.0
3   0.0  10.0  0.0  2.0  4.0
4   0.0   0.0  0.0  0.0  2.0
5   0.0   0.0  8.0  0.0  2.0
6   0.0   0.0  0.0  0.0  2.0
7   0.0   0.0  0.0  0.0  2.0
8   0.0   0.0  0.0  0.0  2.0
9   0.0   0.0  0.0  0.0  2.0
10  0.0   0.0  0.0  0.0  2.0

In [195]:
df

A     B    C    D    E
1   0.0   0.0  0.0  0.0  2.0
2   1.0   0.0  0.0  0.0  2.0
3   0.0  10.0  0.0  2.0  4.0
4   0.0   0.0  0.0  0.0  2.0
5   0.0   0.0  8.0  0.0  2.0
6   0.0   0.0  0.0  0.0  2.0
7   0.0   0.0  0.0  0.0  2.0
8   0.0   0.0  0.0  0.0  2.0
9   0.0   0.0  0.0  0.0  2.0
10  0.0   0.0  0.0  0.0  2.0

In [196]:
# Çözüm
df3 = df.copy()

In [197]:
# df'de yer alan en büyük değer kaçtır?

In [198]:
df[max(value)]

NameError: name 'value' is not defined

In [199]:
 df.max()

A     1.0
B    10.0
C     8.0
D     2.0
E     4.0
dtype: float64

In [200]:
max(df.max())

10.0