In [ ]:
# Online Jupyter: https://jupyter.org/try

In [4]:
deger = 2 * "elma" + 1
print(deger)

TypeError: can only concatenate str (not "int") to str

In [2]:
print(deger)

elmaelma


In [5]:
deger = str(2) + "elma"

In [ ]:
print(deger)

In [ ]:
# elmaelma : Bilal, Enes, Mertcan,
# hata : Nurullah

# Numpy

In [8]:
import numpy as np

In [9]:
liste = [1, 2, 3]

In [10]:
type(liste)

list

In [11]:
np_arr = np.array([1, 2, 3])

In [12]:
type(np_arr)

numpy.ndarray

In [14]:
np.array([[2,3,4],[5,8,7],[9,10,11]])

array([[ 2,  3,  4],
       [ 5,  8,  7],
       [ 9, 10, 11]])

In [15]:
np.zeros(100) # 100 tane 0'dan oluşan numpy array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.zeros((3,5)) # 3 tane 5 adet 0'dan oluşan array oluştur

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3,5)) # 3 tane 5 adet 1'den oluşan array oluştur

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.zeros(3, dtype=int) # Array elemanlarının veri tipi dtype ile belirlenebilir.

array([0, 0, 0])

In [22]:
np.arange(0,10,2) # 0'dan 10'a kadar (10 hariç) 2'şer artan array

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(0,10,50) # 0'dan 10'a kadar (10 dahil) 50 tane nokta oluştur

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
np.eye(5) # 5x5 boyutlarında birim matris oluşturmak için

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.random.rand(5) # 5 tane 0-1 arasında uniform dağılımlı değer oluştur

array([0.69867029, 0.69083726, 0.10601681, 0.7917223 , 0.78920071])

In [41]:
np.random.rand(3,3)

array([[0.94540199, 0.6135649 , 0.51915255],
       [0.52405587, 0.94822354, 0.55847442],
       [0.22853605, 0.73471056, 0.49160087]])

In [51]:
np.random.randint(0,100) # 0 ile 99 arasında rasgele tamsayı oluştur

17

In [52]:
np_arr = np.arange(25)

In [53]:
np_arr.shape

(25,)

In [56]:
np_arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
range(0,25) # Python range bize range nesnesi döndürür

range(0, 25)

In [55]:
np.arange(0,25) # Numpy arange ise bir array döndürür.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
np_arr.shape

(25,)

In [58]:
liste = [2, 3, 4]

In [59]:
2 * liste

[2, 3, 4, 2, 3, 4]

In [7]:
import numpy as np
np_arr = np.array([2, 3, 4])
print(2 * np_arr)

[4 6 8]


In [62]:
2 * np_arr

array([4, 6, 8])

In [64]:
arr = np.arange(25)

In [67]:
arr.max() # Numpy array'in maximum elemanı

24

In [68]:
arr.min() # Numpy array'in minimum elemanı

0

In [69]:
arr.dtype

dtype('int32')

In [71]:
arr[10] # numpy array'in eleman'larına erişim []

10

In [72]:
arr[10:14] # 10 ve 14 (hariç) arası elemanlar: 10, 11, 12, 13 index elemanları

array([10, 11, 12, 13])

In [74]:
b_arr = arr # arr array'inden yeni bir array oluştur, b_arr

In [75]:
b_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
b_arr = np.arange(10)

In [78]:
b_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
# Python liste
a = [1,2,3,4]
b = a
print(b) # [1,2,3,4]
b.append(5)
print(a) # [1,2,3,4,5]
##
b = [3,4]
print(a) # [1,2,3,4,5]

[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [85]:
m5_5 = arr.reshape(5,5)

In [86]:
m5_5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
m5_5[1] # 2. satır

array([5, 6, 7, 8, 9])

In [92]:
m5_5[:,0] # 1. kolon

array([ 0,  5, 10, 15, 20])

In [94]:
m5_5[1:3,2:4] # alt matris oluşturmak için 

array([[ 7,  8],
       [12, 13]])

In [100]:
m5_5[2:5,2:4]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [102]:
m5_5[1:4,2:4]

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [103]:
m5_5[2:5, 2:4]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [109]:
arr = np.random.rand(100)

In [110]:
arr.shape

(100,)

In [116]:
arr > 0.5

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False, False, False, False,  True, False,  True,
       False,  True, False,  True, False, False, False, False,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False, False, False, False,  True,  True, False,  True,  True,
        True, False, False, False,  True,  True, False, False,  True,
       False, False,  True, False,  True, False, False,  True, False,
        True,  True,  True, False, False, False,  True,  True,  True,
       False,  True, False,  True,  True, False, False,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True, False,
        True])

In [118]:
arr[arr > 0.7] # 0.7'den büyük olan arr elemanları

array([0.97139324, 0.99195247, 0.88619033, 0.73112972, 0.92816474,
       0.78951885, 0.87113382, 0.96227462, 0.77189146, 0.71247448,
       0.70345638, 0.7597162 , 0.8167854 , 0.90497107, 0.9334358 ,
       0.94011844, 0.7730561 , 0.87585973, 0.81080891, 0.84782964,
       0.85125216, 0.72963157, 0.78105748, 0.85455873, 0.98023166,
       0.71211847, 0.83801766, 0.95482691, 0.9807981 , 0.86382252])

In [122]:
np.flip(arr) # arr elemanlarını ters'ten listeler

array([0.86382252, 0.34660597, 0.65113265, 0.64975706, 0.9807981 ,
       0.39631695, 0.64647489, 0.95482691, 0.83801766, 0.48304821,
       0.60507168, 0.01708416, 0.71211847, 0.98023166, 0.85455873,
       0.78105748, 0.72963157, 0.18310751, 0.19562039, 0.69067314,
       0.85125216, 0.41169061, 0.42472365, 0.63746374, 0.84782964,
       0.0078877 , 0.81080891, 0.01141968, 0.87585973, 0.7730561 ,
       0.94011844, 0.40043247, 0.24048583, 0.4097788 , 0.9334358 ,
       0.90497107, 0.8167854 , 0.10671029, 0.61641106, 0.24897195,
       0.06925764, 0.7597162 , 0.47602232, 0.51697424, 0.04292049,
       0.43232821, 0.52429666, 0.19020038, 0.2015493 , 0.70345638,
       0.56674314, 0.07951776, 0.16019439, 0.40571206, 0.71247448,
       0.53718499, 0.67140758, 0.37981666, 0.77189146, 0.59846454,
       0.18224752, 0.11197406, 0.42034969, 0.1998563 , 0.96227462,
       0.58630916, 0.58579225, 0.15217726, 0.50164436, 0.87113382,
       0.20315544, 0.17945282, 0.44274463, 0.78951885, 0.04992

In [125]:
arr2 = np.arange(0,11)

In [126]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr2[arr2 % 2 == 0] # arr2'de yer alan çift sayılar

array([ 0,  2,  4,  6,  8, 10])

In [129]:
arr3 = np.arange(100,111)

In [130]:
arr3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [132]:
arr2 + arr3 # array elemanları toplanır

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120])

In [131]:
#python
list_1 = [2,3,4]
list_2 = [3,4,1]
list_1 + list_2

[2, 3, 4, 3, 4, 1]

In [137]:
arr3.argmax()

10

In [138]:
arr3[10]

110

In [140]:
arr2.mean() # array elemanlarının ortalaması

5.0

In [141]:
arr2.sum()

55

In [143]:
np.arange(100).reshape(10,10).mean()

49.5

In [144]:
m10_10 = np.arange(100).reshape(10,10)

In [145]:
m10_10

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [146]:
m10_10.sum() # matrisin bütün elemanlarının toplamı

4950

In [147]:
m10_10.sum(axis=1) # matrisin satırlarının toplamı

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [148]:
m10_10.sum(axis=0) # matrisin kolonlarının toplamı

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [150]:
np.random.randn(10) # normal dağılım, ortalam=0, standart sapma=1

array([ 0.23028357, -0.69512729, -0.2568669 , -0.2589668 ,  0.66670956,
       -0.84227208, -1.98856511,  0.64711324, -0.90240618, -0.56687281])

In [155]:
dist = np.random.randn(100000)
print("Ortalama:"+str(dist.mean()))
print("Standart sapma:"+str(dist.std()))

Ortalama:0.0024199421930186185
Standart sapma:0.9982200437470048


In [ ]:
# ALIŞTIRMALAR

In [156]:
# 10 ile 80 arasında 3'er artan bir numpy array oluşturunuz. [10,13,....79]
np.arange(10,81,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79])

In [157]:
# şu numpy array'i oluşturunuz [3,2,4,5,7,1,2,3]
np.array([3,2,4,5,7,1,2,3])


array([3, 2, 4, 5, 7, 1, 2, 3])

In [ ]:
# numpy kütüphanesini kullanarak kullanarak 0'dan 1000'e kadar 3'er artan sayıların toplamını bulunuz.
# 0,3,6,....999 => toplamını bulunuz?

In [160]:
#Enes
liste = numpy.arange(0,1000,3)
np.sum(liste)

166833

In [161]:
numpy.arange(0,1000,3).sum()

166833

In [162]:
# numpy kütüphanesini kullanarak kullanarak 0'dan 1000'e (1000 hariç) olan sayılardan 
# 2 ve 3 ile kalansız bölünenlerin toplamı.
# Bilal
liste = np.arange(0,1000)
np.sum(liste[liste % 6 == 0])

83166

In [163]:
# Enes
liste = np.arange(0,1000,6)
np.sum(liste)

83166

In [164]:
# Mertcan'ın alıştırma sorusu
# 1000 elemandan oluşan bir listede en büyük elemanın yarısından büyük olanları listeleyin
arr = np.random.randint(0,100,size=1000)

In [168]:
maksimum = arr.max()

In [170]:
maks_yarim = maksimum/2

In [172]:
arr[arr>maks_yarim]

array([79, 84, 63, 87, 71, 50, 55, 86, 51, 70, 91, 58, 52, 74, 99, 95, 81,
       64, 79, 96, 83, 63, 86, 59, 50, 94, 61, 56, 95, 85, 61, 79, 61, 68,
       64, 58, 72, 89, 87, 87, 78, 88, 59, 66, 95, 94, 69, 55, 69, 99, 56,
       57, 71, 73, 74, 62, 77, 52, 84, 69, 58, 72, 72, 59, 90, 81, 57, 54,
       62, 62, 95, 76, 98, 52, 96, 57, 64, 89, 53, 98, 84, 76, 71, 64, 79,
       54, 85, 96, 62, 61, 70, 85, 71, 88, 87, 69, 59, 76, 72, 80, 96, 73,
       60, 73, 86, 71, 89, 56, 73, 90, 68, 96, 63, 90, 59, 52, 50, 89, 71,
       63, 59, 72, 94, 54, 58, 66, 76, 81, 93, 72, 65, 87, 51, 94, 72, 72,
       56, 82, 77, 78, 66, 58, 83, 59, 76, 81, 97, 55, 96, 69, 90, 68, 77,
       62, 77, 96, 68, 64, 53, 57, 86, 86, 82, 78, 68, 57, 73, 64, 76, 64,
       58, 80, 70, 51, 80, 51, 54, 61, 82, 53, 61, 67, 77, 68, 60, 53, 95,
       88, 53, 98, 86, 50, 68, 98, 81, 80, 77, 96, 73, 53, 80, 79, 59, 97,
       91, 56, 67, 53, 71, 50, 61, 98, 85, 65, 53, 76, 90, 53, 53, 74, 55,
       54, 75, 71, 72, 81

In [177]:
# Nurullah
# listede en çok kullanılan harf hangisidir?
isimler = np.array(["Bilal","Nurullah","Mertcan","Feyza","Buğra","Enes","Yasin","Yaşar"])

In [178]:
type(isimler)

numpy.ndarray

In [179]:
for isim in isimler:
    print(isim)

Bilal
Nurullah
Mertcan
Feyza
Buğra
Enes
Yasin
Yaşar


In [186]:
say = {}
for isim in isimler:
    for harf in isim:
        harf=harf.lower()
        if harf in say:
            say[harf]=say[harf]+1
        else:
            say[harf]=0
print(say)


{'b': 1, 'i': 1, 'l': 3, 'a': 7, 'n': 3, 'u': 2, 'r': 3, 'h': 0, 'm': 0, 'e': 3, 't': 0, 'c': 0, 'f': 0, 'y': 2, 'z': 0, 'ğ': 0, 's': 1, 'ş': 0}


In [188]:
counter={}
for element in isimler:
    for char in element:
        char = char.lower()
        if char in counter:
            counter[char] = counter[char] + 1
        else:
            counter[char] = 1
            
print([x for x in counter.keys() if counter[x] == max(counter.values())])

['a']
