## Object Oriented Programming (Nesneye Yönelik Programlama)

In [4]:
liste = [1, 2, 3, 5, 9, 5, 5]

In [5]:
liste.count(5) # 5 sayısının listede kaç tane olduğunu hesapla

3

In [7]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [10]:
len(liste)

7

In [11]:
print(type(liste))

<class 'list'>


In [12]:
tpl = (2,3,4,5)

In [13]:
print(type(tpl))

<class 'tuple'>


## class (sınıf)

In [14]:
class ClassAd:
    pass

In [15]:
x = ClassAd() # ClassAd adlı sınıf bir intance'ı (x)

In [16]:
print(type(x))

<class '__main__.ClassAd'>


In [31]:
class Araba:
    def __init__(self, uretici_, model_, sene_, renk_):
        self.uretici = uretici_
        self.model = model_
        self.sene = sene_
        self.renk = renk_
        
    def ozellikler(self):
        return f"Üretici:{self.uretici}, model:{self.model}, renk:{self.renk}, sene:{self.sene}";
    
    def arabaYas(self, ib_sene):
        return ib_sene - self.sene

In [32]:
araba_1 = Araba("Nissan","Juke",2020,"Siyah") # Nesne-1

In [33]:
araba_2 = Araba("BMW","1.6",2015,"Beyaz") # Nesne-2

In [34]:
araba_3 = Araba(uretici_="Fiat", model_="Egea", sene_="2022", renk_="Kırmızı")

In [22]:
print(type(araba_1))

<class '__main__.Araba'>


In [29]:
araba_1.uretici

'Nissan'

In [24]:
araba_1.sene

2020

In [30]:
print(araba_1.ozellikler())

Üretici:Nissan, model:Juke, renk:Siyah, sene:2020


In [36]:
print(araba_2.arabaYas(2022))

7


## Inheritance (Türetme)

In [78]:
# kiralik araba 
class KiralikAraba(Araba):
    def __init__(self, uretici_, model_, sene_, renk_, dizel_):
        Araba.__init__(self, uretici_, model_, sene_, renk_)
        self.yakit = dizel_
    
    def ozellikler(self): # Polymorhism
        return f"Üretici:{self.uretici}, model:{self.model}, renk:{self.renk}, sene:{self.sene}, yakıt:{self.yakit}";
    
    def kiralanabilirMi(self):
        return True
    
    def __str__(self):
        return "print ile çağrıldığı zaman yazdırılacak içerik"
    

In [79]:
kiralik_araba_1 = KiralikAraba("Mercedes","E200",2015,"Mavi","dizel")

In [80]:
kiralik_araba_2 = KiralikAraba("Tesla","T30",2021,"Siyah","elektrikli")

In [43]:
dir(kiralik_araba_1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'arabaYas',
 'kiralanabilirMi',
 'model',
 'ozellikler',
 'renk',
 'sene',
 'uretici']

In [56]:
araba_1.ozellikler()

'Üretici:Nissan, model:Juke, renk:Siyah, sene:2020'

In [49]:
kiralik_araba_1.yakit

'dizel'

In [51]:
if(kiralik_araba_1.kiralanabilirMi()):
    print("Araç kiralanabilir.")

Araç kiralanabilir.


In [57]:
kiralik_araba_1.ozellikler()

'Üretici:Mercedes, model:E200, renk:Mavi, sene:2015, yakıt:dizel'

In [63]:
dir(KiralikAraba)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__ozel__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'arabaYas',
 'kiralanabilirMi',
 'ozellikler']

In [67]:
kiralik_araba_1.__ozel__()

Bu özel olarak tanımlanmıştır. ozel(nesne_adı)


In [75]:
print(araba_1) # araba_1'in oluşturulduğu class (Araba) __str__ yeniden tanımlanmadı.

In [81]:
print(kiralik_araba_1) # kiralik_araba_1'in oluşturulduğu class (KiralikAraba) __str__ yeniden tanımlandı

print ile çağrıldığı zaman yazdırılacak içerik


In [82]:
kirali_araba_1

In [84]:
del kiralik_araba_1 # kiralik_araba_1 nesnesi yok edilir

In [85]:
del kiralik_araba_2 # kiralik_araba_2 nesnesi yok edilir

In [86]:
class HesKodu:
    def __init__(self, hes_kod_, risk_durumu_):
        self.hes_kod = hes_kod_
        self.risk_durum = risk_durumu_

In [87]:
hes_1 = HesKodu("9009DIIDKE","Risklidir")

In [88]:
hes_1.hes_kod

'9009DIIDKE'

In [96]:
class HesKodu:
    def __init__(self, hes_kod_, risk_durumu_):
        self.__hes_kod = hes_kod_ # hes_kod => private (dışarıdan erişilemeyen bir özellik)
        self.risk_durum = risk_durumu_
        
    def __str__(self):
        return self.__hes_kod

In [97]:
hes_2 = HesKodu("8DIA904DE9","Risksizdir")

In [98]:
hes_2.hes_kod

AttributeError: 'HesKodu' object has no attribute 'hes_kod'

In [99]:
hes_2.__hes_kod

AttributeError: 'HesKodu' object has no attribute '__hes_kod'

In [100]:
hes_2.hes_kod = "8jasdfpasdf"

In [102]:
hes_2.__hes_kod = "8jasdasdfpasdf"

In [103]:
print(hes_2)

8DIA904DE9


## NumPy Kütüphanesi

In [105]:
liste = [3,4,5,6,7,2,3,5,9,5] # => liste'nin elemanlarını 2 ile çarpmak istiyorum: [6, 8, 10, 12, 14, 4, 6, 10, 18, 10]

In [106]:
2 * liste # ?? Doğru sonuç vermez.

[3, 4, 5, 6, 7, 2, 3, 5, 9, 5, 3, 4, 5, 6, 7, 2, 3, 5, 9, 5]

In [107]:
liste2 = []
for rakam in liste:
    liste2.append(rakam * 2)
print(liste2)

[6, 8, 10, 12, 14, 4, 6, 10, 18, 10]


In [108]:
liste3 = [2 * rakam for rakam in liste] # list comprehension
print(liste3)

[6, 8, 10, 12, 14, 4, 6, 10, 18, 10]


In [109]:
import numpy as np # Numpy kütüphanesinin import edilmesi

In [110]:
np_liste = np.array(liste)

In [111]:
print(np_liste)

[3 4 5 6 7 2 3 5 9 5]


In [112]:
type(liste)

list

In [113]:
type(np_liste)

numpy.ndarray

In [114]:
2 * liste

[3, 4, 5, 6, 7, 2, 3, 5, 9, 5, 3, 4, 5, 6, 7, 2, 3, 5, 9, 5]

In [115]:
2 * np_liste

array([ 6,  8, 10, 12, 14,  4,  6, 10, 18, 10])

In [116]:
arr = np.array([1,2,3,4,5,6])

In [117]:
print(arr)

[1 2 3 4 5 6]


In [118]:
print(np.array([1,2,3,4,5.,6]))

[1. 2. 3. 4. 5. 6.]


In [119]:
arr = np.array((1,2,3,4,5,6))

In [120]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [121]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [122]:
arr2.ndim # Bir numpy array'inin kaç boyutlu olduğunu öğrenmek için

2

In [123]:
arr.ndim

1

In [124]:
arr[1]

2

In [126]:
arr[2:4] # indekler 2 ve 3 gösterilir (4 hariç)

array([3, 4])

In [127]:
arr = np.arange(1,100) # 1 den 100'e kadar (100 hariç) bir numpy array oluştur

In [128]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [129]:
arr.shape

(99,)

In [130]:
arr.ndim

1

In [132]:
arr2 = arr.reshape(9,11)

In [133]:
arr2.shape

(9, 11)

In [136]:
for rakam in arr2:
    print(rakam)

[ 1  2  3  4  5  6  7  8  9 10 11]
[12 13 14 15 16 17 18 19 20 21 22]
[23 24 25 26 27 28 29 30 31 32 33]
[34 35 36 37 38 39 40 41 42 43 44]
[45 46 47 48 49 50 51 52 53 54 55]
[56 57 58 59 60 61 62 63 64 65 66]
[67 68 69 70 71 72 73 74 75 76 77]
[78 79 80 81 82 83 84 85 86 87 88]
[89 90 91 92 93 94 95 96 97 98 99]


In [137]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,10,11])
# iki array birleştirmek => [1,2,3,9,10,11]

In [139]:
arr = np.concatenate((arr1, arr2))

In [144]:
print(arr)

[ 1  2  3  9 10 11]


In [145]:
arr_cift_index = np.where(arr % 2 == 0) 
# Çift sayıların filtrelenmesi. np.where çift olan array elemanlarının İNDEKS değerlerini döndürür.

In [146]:
print(arr_cift) # index değerleri

(array([1, 4], dtype=int64),)


In [147]:
arr[arr_cift] # index değerlerinin kullanarak orjinal array'in değerlerine erişim.

array([ 2, 10])

In [148]:
arr = np.array([4,1,6,3,2,9])

In [149]:
np.sort(arr)

array([1, 2, 3, 4, 6, 9])

In [150]:
arrTek = arr % 2 == 1 # numpy ile filtreleme

In [151]:
arr[arrTek]

array([1, 3, 9])

arrTek

## Uygulamalar

In [154]:
# Bir Dikdortgen Class'ı oluşturunuz.
# 2. Dikdortgen Class'ında alan ve çevre hesaplayan iki tane oluşturunuz

In [163]:
class Dikdortgen:
    def __init__(self, kisaKenar, uzunKenar):
        self.kisaKenar = kisaKenar
        self.uzunKenar = uzunKenar

    def alan(self): # a * b
        return self.kisaKenar * self.uzunKenar
    
    def cevre(self): # 2 * (a + b)
        return 2 * (self.kisaKenar + self.uzunKenar)

In [159]:
# Dikdorgen Class'ını kullanarak 2 tane nesne oluşturunuz?

In [164]:
dikdortgen1 = Dikdortgen(30,60)
dikdortgen2 = Dikdortgen(5,8)

In [165]:
dikdortgen3 = Dikdortgen(20,49)

In [166]:
dikdortgen4 = Dikdortgen(48,52)

In [168]:
dikdortgen1.alan()

1800

In [169]:
dikdortgen1.cevre()

180

In [170]:
# Numpy
arr = np.array([1, 2, 3, 4, 5])

In [171]:
# arr numpy array'inin 3. elemanını print ediniz?

In [172]:
 print(arr[2])

3


In [173]:
# arr numpy array'inin elemanlarını 3 ile çarpınız. [3,6,9,12,15]

In [174]:
arr * 3

array([ 3,  6,  9, 12, 15])

In [175]:
# arr numpy array'inin elemanlarını 1 arttırınız => [2,3,4,5,6]

In [176]:
arr + 1

array([2, 3, 4, 5, 6])

In [177]:
liste = [1, 2, 3, 4, 5]

In [178]:
liste + 1

TypeError: can only concatenate list (not "int") to list

In [179]:
[rakam+1 for rakam in liste]

[2, 3, 4, 5, 6]

In [180]:
arr

array([1, 2, 3, 4, 5])

In [181]:
np.random.shuffle(arr)

In [182]:
arr

array([1, 3, 4, 2, 5])

In [183]:
# arr numpy array'ini shuffle ile sürekli karıştırarak 3. eleman değeri (index=2) 2 olunca durunuz.

In [184]:
print(arr)

[1 3 4 2 5]


In [207]:
np.random.shuffle(arr)
print(arr)

[3 2 1 5 4]


In [206]:
print(arr)
while arr[2] != 2:
    np.random.shuffle(arr)
    print(arr)

[3 4 1 2 5]
[2 5 4 3 1]
[4 3 5 1 2]
[2 5 1 3 4]
[5 4 2 3 1]


In [ ]:
np.random.shuffle(arr)
print(arr)

In [208]:
 for rakam in arr:
    np.random.shuffle(arr)
    if rakam == 2:
        print("2.sayı", rakam)
        break

In [277]:
np.random.randint(100)

66

In [278]:
# numpy.random'ın randint fonksiyonu gerçekten rasgele sayılar üretiyor mu kontrol ediniz?
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [279]:
basla = np.zeros(100)

In [286]:
for test in range(1000000):
    deger = np.random.randint(100)
    basla[deger] = basla[deger] + 1

In [288]:
print(basla/10000)

[1.1139 1.1301 1.119  1.1121 1.1035 1.1025 1.1258 1.1177 1.1151 1.107
 1.1127 1.1124 1.1037 1.1126 1.1081 1.1079 1.1044 1.1246 1.1274 1.1223
 1.126  1.1012 1.1108 1.1161 1.1171 1.1191 1.1049 1.1038 1.1054 1.1104
 1.1188 1.1078 1.1099 1.1023 1.1189 1.0979 1.1193 1.0782 1.1041 1.1068
 1.1275 1.0761 1.1165 1.1128 1.0949 1.1196 1.1051 1.1124 1.1081 1.1089
 1.1074 1.1149 1.1162 1.1143 1.1124 1.1234 1.1001 1.0941 1.1248 1.1053
 1.1278 1.1158 1.096  1.0882 1.1114 1.1024 1.116  1.1196 1.0989 1.1084
 1.1122 1.1047 1.1294 1.1137 1.1203 1.1122 1.1087 1.1123 1.1059 1.1004
 1.1122 1.1193 1.1139 1.1163 1.0878 1.1159 1.1191 1.1202 1.1077 1.1233
 1.1123 1.1156 1.1044 1.1201 1.1061 1.0894 1.1049 1.1226 1.1196 1.1086]


In [289]:
# https://www.w3schools.com/python/default.asp